name: Update RSS feed

on:
  push:
  schedule:
    - cron: '00 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MSFS_RSS_PAT }}

      - name: Install Python modules
        run: pip3 install -r requirements.txt

      - name: Update Feed
        run: python3 main.py

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'atom.xml'
          default_author: github_actions
          message: 'RSS feed update'
          pull_strategy: 'NO-PULL'
