name: Update RSS feeds

on:
  schedule:
    - cron: '00 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }} # Personal Access Token with repo scope

      - name: Install Python modules
        run: pip3 install -r requirements.txt

      - name: Update MSFS feed
        run: python3 src/msfs.py

      - name: Update thresholdx feed
        run: python3 src/thresholdx.py

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'feeds/*.xml'
          default_author: github_actions
          message: 'RSS feed update'
          pull_strategy: 'NO-PULL'
